### PR TITLE
Prevent race conditions when resizing window

### LINKED ISSUE #1125: Data race condition detected when resizing main window
### Describe the bug

When resizing the main window a data race condition is detected.

### How to reproduce

1) Open a main window.
2) Run the program with the Go race detector enabled.
3) Resize the main window, data race is detected.

### Example code

```go
b := core.NewBody("Test")
b.RunMainWindow()
```

### Relevant output

```shell
==================
WARNING: DATA RACE
Read at 0x00c000185718 by goroutine 40:
  cogentcore.org/core/system/driver/base.(*Window[go.shape.*uint8]).Is()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/system/driver/base/window.go:147 +0x84
  cogentcore.org/core/system/driver/base.(*Window[go.shape.*uint8]).IsVisible()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/system/driver/base/window.go:155 +0x18
  cogentcore.org/core/system/driver/base.(*WindowMulti[go.shape.*uint8,go.shape.*uint8]).IsVisible()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/system/driver/base/window_multi.go:144 +0x50
  cogentcore.org/core/system/driver/desktop.(*Window).IsVisible()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/system/driver/desktop/window.go:37 +0x34
  cogentcore.org/core/core.(*renderWindow).isVisible()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/renderwindow.go:368 +0xb4
  cogentcore.org/core/core.(*renderWindow).resized()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/renderwindow.go:266 +0x4c
  cogentcore.org/core/core.(*renderWindow).handleWindowEvents()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/renderwindow.go:462 +0x64c
  cogentcore.org/core/core.(*renderWindow).handleEvent()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/renderwindow.go:440 +0x168
  cogentcore.org/core/core.(*renderWindow).eventLoop()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/renderwindow.go:408 +0xd0
  cogentcore.org/core/core.(*renderWindow).goStartEventLoop.gowrap1()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/renderwindow.go:379 +0x34

Previous write at 0x00c000185718 by main goroutine:
  ??()
      -:0 +0x1052dea34
  sync/atomic.StoreInt64()
      <autogenerated>:1 +0x14
  cogentcore.org/core/system.(*WindowFlags).SetFlag()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/system/enumgen.go:144 +0x94
  cogentcore.org/core/system/driver/desktop.(*Window).UpdateFullscreen()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/system/driver/desktop/window.go:361 +0x24
  cogentcore.org/core/system/driver/desktop.(*Window).WinResized()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/system/driver/desktop/window.go:356 +0x28
  cogentcore.org/core/system/driver/desktop.(*Window).WinResized-fm()
      <autogenerated>:1 +0x4c
  github.com/go-gl/glfw/v3.3/glfw.goWindowSizeCB()
      /Users/test/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20240307211618-a69d953ea142/window.go:212 +0x70
  _cgoexp_16379c6f66fe_goWindowSizeCB()
      _cgo_gotypes.go:2666 +0x68
  runtime.cgocallbackg1()
      /opt/homebrew/Cellar/go/1.22.6/libexec/src/runtime/cgocall.go:420 +0x238
  cogentcore.org/core/system/driver/desktop.(*App).MainLoop()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/system/driver/desktop/app.go:71 +0x18c
  cogentcore.org/core/core.Wait()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/renderwindow.go:41 +0x80
  cogentcore.org/core/core.(*Body).RunMainWindow()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/mainstage.go:46 +0x5c
  main.main()
      /Users/test/Dev/test/test.go:87 +0x38c

Goroutine 40 (running) created at:
  cogentcore.org/core/core.(*renderWindow).goStartEventLoop()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/renderwindow.go:379 +0x94
  cogentcore.org/core/core.(*Stage).runWindow()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/mainstage.go:246 +0x83c
  cogentcore.org/core/core.(*Stage).run()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/stage.go:280 +0xb4
  cogentcore.org/core/core.(*Stage).Run()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/stage.go:259 +0xc8
  cogentcore.org/core/core.(*Body).RunWindow()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/mainstage.go:71 +0x98
  cogentcore.org/core/core.(*Body).RunMainWindow()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/mainstage.go:45 +0x58
  main.main()
      /Users/test/Dev/test/test.go:87 +0x38c
==================
==================
WARNING: DATA RACE
Read at 0x00c000185838 by goroutine 40:
  cogentcore.org/core/system/driver/base.(*WindowMulti[go.shape.*uint8,go.shape.*uint8]).Size()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/system/driver/base/window_multi.go:77 +0x3c
  cogentcore.org/core/system/driver/desktop.(*Window).Size()
      <autogenerated>:1 +0x20
  cogentcore.org/core/system/driver/base.(*Window[go.shape.*uint8]).RenderGeom()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/system/driver/base/window.go:168 +0x48
  cogentcore.org/core/system/driver/desktop.(*Window).RenderGeom()
      <autogenerated>:1 +0x20
  cogentcore.org/core/core.(*renderWindow).resized()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/renderwindow.go:273 +0x98
  cogentcore.org/core/core.(*renderWindow).handleWindowEvents()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/renderwindow.go:462 +0x64c
  cogentcore.org/core/core.(*renderWindow).handleEvent()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/renderwindow.go:440 +0x168
  cogentcore.org/core/core.(*renderWindow).eventLoop()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/renderwindow.go:408 +0xd0
  cogentcore.org/core/core.(*renderWindow).goStartEventLoop.gowrap1()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/renderwindow.go:379 +0x34

Previous write at 0x00c000185838 by main goroutine:
  cogentcore.org/core/system/driver/desktop.(*Window).UpdateGeom()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/system/driver/desktop/window.go:376 +0x108
  cogentcore.org/core/system/driver/desktop.(*Window).WinResized()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/system/driver/desktop/window.go:357 +0x30
  cogentcore.org/core/system/driver/desktop.(*Window).WinResized-fm()
      <autogenerated>:1 +0x4c
  github.com/go-gl/glfw/v3.3/glfw.goWindowSizeCB()
      /Users/test/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20240307211618-a69d953ea142/window.go:212 +0x70
  _cgoexp_16379c6f66fe_goWindowSizeCB()
      _cgo_gotypes.go:2666 +0x68
  runtime.cgocallbackg1()
      /opt/homebrew/Cellar/go/1.22.6/libexec/src/runtime/cgocall.go:420 +0x238
  cogentcore.org/core/system/driver/desktop.(*App).MainLoop()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/system/driver/desktop/app.go:71 +0x18c
  cogentcore.org/core/core.Wait()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/renderwindow.go:41 +0x80
  cogentcore.org/core/core.(*Body).RunMainWindow()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/mainstage.go:46 +0x5c
  main.main()
      /Users/test/Dev/test/test.go:87 +0x38c

Goroutine 40 (running) created at:
  cogentcore.org/core/core.(*renderWindow).goStartEventLoop()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/renderwindow.go:379 +0x94
  cogentcore.org/core/core.(*Stage).runWindow()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/mainstage.go:246 +0x83c
  cogentcore.org/core/core.(*Stage).run()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/stage.go:280 +0xb4
  cogentcore.org/core/core.(*Stage).Run()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/stage.go:259 +0xc8
  cogentcore.org/core/core.(*Body).RunWindow()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/mainstage.go:71 +0x98
  cogentcore.org/core/core.(*Body).RunMainWindow()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/mainstage.go:45 +0x58
  main.main()
      /Users/test/Dev/test/test.go:87 +0x38c
==================
==================
WARNING: DATA RACE
Read at 0x00c000185718 by goroutine 40:
  cogentcore.org/core/system/driver/base.(*Window[go.shape.*uint8]).Is()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/system/driver/base/window.go:147 +0x84
  cogentcore.org/core/system/driver/base.(*Window[go.shape.*uint8]).IsVisible()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/system/driver/base/window.go:155 +0x18
  cogentcore.org/core/system/driver/base.(*WindowMulti[go.shape.*uint8,go.shape.*uint8]).IsVisible()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/system/driver/base/window_multi.go:144 +0x50
  cogentcore.org/core/system/driver/desktop.(*Window).IsVisible()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/system/driver/desktop/window.go:37 +0x34
  cogentcore.org/core/core.(*renderWindow).isVisible()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/renderwindow.go:368 +0xb4
  cogentcore.org/core/core.(*renderWindow).drawScenes()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/renderwindow.go:780 +0x30
  cogentcore.org/core/core.(*renderWindow).renderWindow()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/renderwindow.go:775 +0x34c
  cogentcore.org/core/core.(*renderWindow).handleWindowEvents()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/renderwindow.go:456 +0x61c
  cogentcore.org/core/core.(*renderWindow).handleEvent()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/renderwindow.go:440 +0x168
  cogentcore.org/core/core.(*renderWindow).eventLoop()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/renderwindow.go:408 +0xd0
  cogentcore.org/core/core.(*renderWindow).goStartEventLoop.gowrap1()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/renderwindow.go:379 +0x34

Previous write at 0x00c000185718 by main goroutine:
  ??()
      -:0 +0x1052dea34
  sync/atomic.StoreInt64()
      <autogenerated>:1 +0x14
  cogentcore.org/core/system.(*WindowFlags).SetFlag()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/system/enumgen.go:144 +0x94
  cogentcore.org/core/system/driver/desktop.(*Window).UpdateFullscreen()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/system/driver/desktop/window.go:361 +0x24
  cogentcore.org/core/system/driver/desktop.(*Window).WinResized()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/system/driver/desktop/window.go:356 +0x28
  cogentcore.org/core/system/driver/desktop.(*Window).WinResized-fm()
      <autogenerated>:1 +0x4c
  github.com/go-gl/glfw/v3.3/glfw.goWindowSizeCB()
      /Users/test/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20240307211618-a69d953ea142/window.go:212 +0x70
  _cgoexp_16379c6f66fe_goWindowSizeCB()
      _cgo_gotypes.go:2666 +0x68
  runtime.cgocallbackg1()
      /opt/homebrew/Cellar/go/1.22.6/libexec/src/runtime/cgocall.go:420 +0x238
  cogentcore.org/core/system/driver/desktop.(*App).MainLoop()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/system/driver/desktop/app.go:71 +0x18c
  cogentcore.org/core/core.Wait()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/renderwindow.go:41 +0x80
  cogentcore.org/core/core.(*Body).RunMainWindow()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/mainstage.go:46 +0x5c
  main.main()
      /Users/test/Dev/test/test.go:87 +0x38c

Goroutine 40 (running) created at:
  cogentcore.org/core/core.(*renderWindow).goStartEventLoop()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/renderwindow.go:379 +0x94
  cogentcore.org/core/core.(*Stage).runWindow()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/mainstage.go:246 +0x83c
  cogentcore.org/core/core.(*Stage).run()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/stage.go:280 +0xb4
  cogentcore.org/core/core.(*Stage).Run()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/stage.go:259 +0xc8
  cogentcore.org/core/core.(*Body).RunWindow()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/mainstage.go:71 +0x98
  cogentcore.org/core/core.(*Body).RunMainWindow()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/mainstage.go:45 +0x58
  main.main()
      /Users/test/Dev/test/test.go:87 +0x38c
==================
==================
WARNING: DATA RACE
Read at 0x00c000185718 by goroutine 40:
  cogentcore.org/core/system/driver/base.(*Window[go.shape.*uint8]).Is()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/system/driver/base/window.go:147 +0x84
  cogentcore.org/core/system/driver/base.(*Window[go.shape.*uint8]).IsVisible()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/system/driver/base/window.go:155 +0x18
  cogentcore.org/core/system/driver/base.(*WindowMulti[go.shape.*uint8,go.shape.*uint8]).IsVisible()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/system/driver/base/window_multi.go:144 +0x50
  cogentcore.org/core/system/driver/desktop.(*Window).IsVisible()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/system/driver/desktop/window.go:37 +0x34
  cogentcore.org/core/core.(*renderWindow).isVisible()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/renderwindow.go:368 +0xb4
  cogentcore.org/core/core.(*windowGeometrySaver).recordPref()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/windowgeometry.go:234 +0x34
  cogentcore.org/core/core.(*renderWindow).resized()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/renderwindow.go:310 +0x4e4
  cogentcore.org/core/core.(*renderWindow).handleWindowEvents()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/renderwindow.go:462 +0x64c
  cogentcore.org/core/core.(*renderWindow).handleEvent()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/renderwindow.go:440 +0x168
  cogentcore.org/core/core.(*renderWindow).eventLoop()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/renderwindow.go:408 +0xd0
  cogentcore.org/core/core.(*renderWindow).goStartEventLoop.gowrap1()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/renderwindow.go:379 +0x34

Previous write at 0x00c000185718 by main goroutine:
  ??()
      -:0 +0x1052dea34
  sync/atomic.StoreInt64()
      <autogenerated>:1 +0x14
  cogentcore.org/core/system.(*WindowFlags).SetFlag()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/system/enumgen.go:144 +0x94
  cogentcore.org/core/system/driver/desktop.(*Window).UpdateFullscreen()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/system/driver/desktop/window.go:361 +0x24
  cogentcore.org/core/system/driver/desktop.(*Window).Moved()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/system/driver/desktop/window.go:350 +0x78
  cogentcore.org/core/system/driver/desktop.(*Window).Moved-fm()
      <autogenerated>:1 +0x4c
  github.com/go-gl/glfw/v3.3/glfw.goWindowPosCB()
      /Users/test/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20240307211618-a69d953ea142/window.go:206 +0x70
  _cgoexp_16379c6f66fe_goWindowPosCB()
      _cgo_gotypes.go:2656 +0x68
  runtime.cgocallbackg1()
      /opt/homebrew/Cellar/go/1.22.6/libexec/src/runtime/cgocall.go:420 +0x238
  cogentcore.org/core/system/driver/desktop.(*App).MainLoop()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/system/driver/desktop/app.go:71 +0x18c
  cogentcore.org/core/core.Wait()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/renderwindow.go:41 +0x80
  cogentcore.org/core/core.(*Body).RunMainWindow()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/mainstage.go:46 +0x5c
  main.main()
      /Users/test/Dev/test/test.go:87 +0x38c

Goroutine 40 (running) created at:
  cogentcore.org/core/core.(*renderWindow).goStartEventLoop()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/renderwindow.go:379 +0x94
  cogentcore.org/core/core.(*Stage).runWindow()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/mainstage.go:246 +0x83c
  cogentcore.org/core/core.(*Stage).run()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/stage.go:280 +0xb4
  cogentcore.org/core/core.(*Stage).Run()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/stage.go:259 +0xc8
  cogentcore.org/core/core.(*Body).RunWindow()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/mainstage.go:71 +0x98
  cogentcore.org/core/core.(*Body).RunMainWindow()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/mainstage.go:45 +0x58
  main.main()
      /Users/test/Dev/test/test.go:87 +0x38c
==================
==================
WARNING: DATA RACE
Write at 0x000105ea9ad8 by main goroutine:
  cogentcore.org/core/system/driver/desktop.(*App).GetScreens()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/system/driver/desktop/screen.go:70 +0x1f4
  cogentcore.org/core/system/driver/desktop.(*App).MonitorChange()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/system/driver/desktop/screen.go:39 +0x154
  cogentcore.org/core/system/driver/desktop.(*App).MonitorChange-fm()
      <autogenerated>:1 +0x44
  github.com/go-gl/glfw/v3.3/glfw.goMonitorCB()
      /Users/test/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20240307211618-a69d953ea142/monitor.go:52 +0x94
  _cgoexp_16379c6f66fe_goMonitorCB()
      _cgo_gotypes.go:2646 +0x24
  runtime.cgocallbackg1()
      /opt/homebrew/Cellar/go/1.22.6/libexec/src/runtime/cgocall.go:420 +0x238
  cogentcore.org/core/system/driver/desktop.(*App).MainLoop()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/system/driver/desktop/app.go:71 +0x18c
  cogentcore.org/core/core.Wait()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/renderwindow.go:41 +0x80
  cogentcore.org/core/core.(*Body).RunMainWindow()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/mainstage.go:46 +0x5c
  main.main()
      /Users/test/Dev/test/test.go:87 +0x38c

Previous read at 0x000105ea9ad8 by goroutine 40:
  cogentcore.org/core/system/driver/desktop.(*Window).GetScreenOverlap()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/system/driver/desktop/window.go:161 +0x90
  cogentcore.org/core/system/driver/desktop.(*Window).Screen()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/system/driver/desktop/window.go:133 +0x2b8
  cogentcore.org/core/core.(*windowGeometrySaver).recordPref()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/windowgeometry.go:262 +0x598
  cogentcore.org/core/core.(*renderWindow).handleWindowEvents()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/renderwindow.go:491 +0x150
  cogentcore.org/core/core.(*renderWindow).handleEvent()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/renderwindow.go:440 +0x168
  cogentcore.org/core/core.(*renderWindow).eventLoop()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/renderwindow.go:408 +0xd0
  cogentcore.org/core/core.(*renderWindow).goStartEventLoop.gowrap1()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/renderwindow.go:379 +0x34

Goroutine 40 (running) created at:
  cogentcore.org/core/core.(*renderWindow).goStartEventLoop()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/renderwindow.go:379 +0x94
  cogentcore.org/core/core.(*Stage).runWindow()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/mainstage.go:246 +0x83c
  cogentcore.org/core/core.(*Stage).run()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/stage.go:280 +0xb4
  cogentcore.org/core/core.(*Stage).Run()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/stage.go:259 +0xc8
  cogentcore.org/core/core.(*Body).RunWindow()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/mainstage.go:71 +0x98
  cogentcore.org/core/core.(*Body).RunMainWindow()
      /Users/test/go/pkg/mod/cogentcore.org/core@v0.3.1/core/mainstage.go:45 +0x58
  main.main()
      /Users/test/Dev/test/test.go:87 +0x38c
==================
```

### Platform

macOS

### PR DESCRIPTION
**Pull request by kkoreilly**
The main race condition was caused by `enums.BitFlag.HasFlag` not having a pointer receiver. I fixed that, but there are still some race conditions remaining, largely pertaining to window geometry.

Fixes #1125

### CODE REVIEW

**Comment by kkoreilly** [comment]
By protecting window geometry with mutexes, fixing the bit flag atomic handling, and making more things bit flags, all of the core race conditions appear to be resolved now.

**Review by rcoreilly — APPROVED** [review]
How do we notify current users that they need to reinstall core command?

**Comment by kkoreilly** [comment]
I doubt that any current user is using core bit flag enums, but I will add a note to the draft release notes, since people definitely do need to reinstall it for HTML preview / SEO, WebGPU, and GopherJS (https://github.com/cogentcore/cogentcore.github.io/commit/d579ca0cfda6ca30aa617532f05e83b39f129d16).

**Comment by theclapp** [comment]
> How do we notify current users that they need to reinstall core command?

Data point: I reinstall cmd/core (or did you mean something else?) every time I "git pull". It usually needs it.

**Comment by kkoreilly** [comment]
Yes, that is a good strategy. We should probably recommend people re-install frequently in the install docs, and then also remind people in the release notes for each release.

**Comment by kkoreilly** [comment]
See #1167.

**Pull request merged**
