### PR TITLE
Support customizing the icon of tree view branch switches

### PR DESCRIPTION
**Pull request by ddkwork**

### CODE REVIEW

**Comment by ddkwork** [comment]
I read the source code of the tree widget and found that you can customize the hierarchical display icon of the tree widget just by setting the icon of the Switch widget, but I didn't find where to read the svg file buffer after it reads the file name from the icons package, the icons package doesn't seem to need to implement any interface, but you need to pay attention to the naming of the svg file name, but since it is a custom widget property, I want to pass the svg filename and buffer directly from outside instead of adding the svg file to the icons package. So my question is, under which code does the Switch widget read the svg file buffer? Get this in order to write the icon of the Switch widget to set the callback parameter, and then set the tree widget icon

**Comment by kkoreilly** [comment]
The icons of the switch are set on line 252 of `giv/treeview.go`. Instead of hard-coding the values passed there, you should pass the values of the fields you will add on the treeview.

We do not currently support icons that are not part of the icons library, and we will work on improving our support for that soon in the context of #740.

**Comment by kkoreilly** [comment]
And please do ***not*** sync your fork when you have a PR in progress, as it resets it. You only need to sync it between PRs.

**Comment by ddkwork** [comment]
> The icons of the switch are set on line 252 of `giv/treeview.go`. Instead of hard-coding the values passed there, you should pass the values of the fields you will add on the treeview.
> 
> We do not currently support icons that are not part of the icons library, and we will work on improving our support for that soon in the context of #740.

It's done, but I don't think the PR worked well this time

**Comment by ddkwork** [comment]
> And please do ***not*** sync your fork when you have a PR in progress, as it resets it. You only need to sync it between PRs.

okay

**Review by kkoreilly — CHANGES_REQUESTED** [review]
Please also add `IconUnk` to the `TreeView` and pass it in `sw.SetIcons`. Also, instead of adding a safety check at the point at which you set the icons, you should set default values for the icons on the `TreeView` in its `OnInit` function. There should be no other `SetIcons` calls or if statements at the point you set the icons. Thanks!

**Comment by ddkwork** [comment]
> Please also add `IconUnk` to the `TreeView` and pass it in `sw.SetIcons`. Also, instead of adding a safety check at the point at which you set the icons, you should set default values for the icons on the `TreeView` in its `OnInit` function. There should be no other `SetIcons` calls or if statements at the point you set the icons. Thanks!

Is that so? How to assert the swich pointer in the init function, I don't know how to change it here, or you can change the code

**Comment by kkoreilly** [comment]
Change line 362 of `treeview.go` to `sw.SetIcons(tv.IconOn, tv.IconOff, tv.IconUnk)`. Then, at line 201 of `treeview.go`, set the icon fields of the treeview to the default values (`tv.IconOn = icons.KeyboardArrowDown` etc).

**Comment by ddkwork** [comment]
> Change line 362 of `treeview.go` to `sw.SetIcons(tv.IconOn, tv.IconOff, tv.IconUnk)`. Then, at line 201 of `treeview.go`, set the icon fields of the treeview to the default values (`tv.IconOn = icons.KeyboardArrowDown` etc).

You can change it. I can't get out of it today, I'm going to have to go far now, I'm sorry, I fell asleep last night

**Review by kkoreilly — APPROVED** [review]

**Comment by kkoreilly** [comment]
I applied the rest of the changes and cleaned things up. Thanks for all of your work on this PR!

You should use `icons.ExpandCircleDown` and `icons.ExpandCircleRight` instead of `icons.DownCircleOutlined` and `icons.RightCircleOutlined`. Also, for future reference, it would be better if you didn't edit documentation comments.

**Comment by rcoreilly** [comment]
More appropriate names for icons would be: `Open, Closed`, and `Leaf` (terminal node, no children) -- we are using the switch states of On, Off, Unk but these are not semantically relevant for the tree case.

**Comment by ddkwork** [comment]
> I applied the rest of the changes and cleaned things up. Thanks for all of your work on this PR!
> 
> You should use `icons.ExpandCircleDown` and `icons.ExpandCircleRight` instead of `icons.DownCircleOutlined` and `icons.RightCircleOutlined`. Also, for future reference, it would be better if you didn't edit documentation comments.

Thank you very much for modifying the code, let me learn a lot. It was a very tiring day, I had a bad cold, and I had to do manual work, but my interests were computers and programming, and it backfired, and I was confused

**Comment by ddkwork** [comment]
> More appropriate names for icons would be: `Open, Closed`, and `Leaf` (terminal node, no children) -- we are using the switch states of On, Off, Unk but these are not semantically relevant for the tree case.
> 

I agree with you, and I'd like to propose changing all names that appear idx or the like to index,and all par change to parent.

**Comment by kkoreilly** [comment]
> It was a very tiring day, I had a bad cold, and I had to do manual work, but my interests were computers and programming, and it backfired, and I was confused

I hope you feel better soon! I will change the names of the tree view icons to `Open`, `Closed`, and `Leaf`, and I will consider changing the names containing Idx and Par.

**Comment by ddkwork** [comment]
> `icons.ExpandCircleDown``icons.ExpandCircleRight``icons.DownCircleOutlined``icons.RightCircleOutlined`

thanks

**Comment by ddkwork** [comment]
> icons.RightCircleOutlined. Also, for future reference

I don't know why, the icons of the other parent nodes are not refreshing

**Comment by kkoreilly** [comment]
This should be fixed now.

**Comment by ddkwork** [comment]
> This should be fixed now.

thanks

**Pull request merged**
